// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Arl0F80QrBt63Xj9A3KZyZ2xGMkmOB4',
    appId: '1:446972964828:web:f32831eb3139e9dd5ee919',
    messagingSenderId: '446972964828',
    projectId: 'ourbookshelf-db06a',
    authDomain: 'ourbookshelf-db06a.firebaseapp.com',
    storageBucket: 'ourbookshelf-db06a.appspot.com',
    measurementId: 'G-525G37D25Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkwToedUs4o9g5cYz3ePSnkLqM_APqGug',
    appId: '1:446972964828:android:ecf611c061ca58415ee919',
    messagingSenderId: '446972964828',
    projectId: 'ourbookshelf-db06a',
    storageBucket: 'ourbookshelf-db06a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7kb-EoTLwT4hwLiLlY-Fi2gk_k5fAeuM',
    appId: '1:446972964828:ios:d67e4ce3f77d6e3a5ee919',
    messagingSenderId: '446972964828',
    projectId: 'ourbookshelf-db06a',
    storageBucket: 'ourbookshelf-db06a.appspot.com',
    iosClientId: '446972964828-0o250ait406mu40t42cuspr9994k11ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourBookshelfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7kb-EoTLwT4hwLiLlY-Fi2gk_k5fAeuM',
    appId: '1:446972964828:ios:d67e4ce3f77d6e3a5ee919',
    messagingSenderId: '446972964828',
    projectId: 'ourbookshelf-db06a',
    storageBucket: 'ourbookshelf-db06a.appspot.com',
    iosClientId: '446972964828-0o250ait406mu40t42cuspr9994k11ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourBookshelfApp',
  );
}
